### ISSUE TITLE
Support for more than one WH2 transmitter?

### ISSUE THREAD

**Issue by pianomansam** [lucsmall/BetterWH2#1]
Does your code support more than one WH2 transmitter? In reading your blog articles, I see you are only experimenting with one, yet apparently up to three can be used at once (http://www.ambientweather.com/amws0100combokit.html).

**Comment by lucsmall** [comment]
I can confirm that it works fine with two transmitters and should support quite a few more. The key things to watch are that no two transmitters broadcast simultaneously (since they will clobber each other's signals). But a collision is unlikely given each transmitter is only active for ~100ms every 48 seconds. The other thing is that each transmitter gets a different ID, so you can distinguish them. Removing and re-inserting the batteries will assign a new ID.

I believe the "3 transmitter" limit is a limitation of the original receiver unit.

**Comment by pianomansam** [comment]
Awesome. Thanks so much for the quick reply! I'm going to attempt to use several WH2's as temperature sensors for my custom arduino furnace thermostat.
